Controller: Wait for scoreboard thread in tests to prevent race condition
Recently, the tests in test_main_loop.py started to fail randomly. The
same setup from .devcontainer.json half a year ago worked fine.

The following exception is thrown when the test fails:

    Exception in thread Thread-3 (calculate):
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
        self.run()
      File "/usr/local/lib/python3.11/threading.py", line 982, in run
        self._target(*self._args, **self._kwargs)
      File "/home/test/ctf-gameserver/src/ctf_gameserver/controller/controller.py", line 217, in calculate
        scoring.calculate_scoreboard(db_conn)
      File "/home/test/ctf-gameserver/src/ctf_gameserver/controller/scoring.py", line 89, in calculate_scoreboard
        cursor.execute('DELETE FROM scoring_scoreboard')
      File "/home/test/ctf-gameserver/src/ctf_gameserver/lib/database.py", line 59, in sqlite3_execute
        return self._orig_cursor.execute(operation, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    sqlite3.OperationalError: database table is locked

This causes another exception while Django tries to cleanup the database
after running the test:

    Traceback (most recent call last):
      File "/home/test/ctf-gameserver/.venv/lib/python3.11/site-packages/django/core/management/commands/flush.py", line 63, in handle
        connection.ops.execute_sql_flush(sql_list)
      File "/home/test/ctf-gameserver/.venv/lib/python3.11/site-packages/django/db/backends/base/operations.py", line 411, in execute_sql_flush
        cursor.execute(sql)
      File "/home/test/ctf-gameserver/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 98, in execute
        return super().execute(sql, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/test/ctf-gameserver/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 66, in execute
        return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/test/ctf-gameserver/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
        return executor(sql, params, many, context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/test/ctf-gameserver/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in _execute
        with self.db.wrap_database_errors:
      File "/home/test/ctf-gameserver/.venv/lib/python3.11/site-packages/django/db/utils.py", line 90, in __exit__
        raise dj_exc_value.with_traceback(traceback) from exc_value
      File "/home/test/ctf-gameserver/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 82, in _execute
        return self.cursor.execute(sql)
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/test/ctf-gameserver/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 421, in execute
        return Database.Cursor.execute(self, query)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    django.db.utils.OperationalError: database table is locked

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/home/test/ctf-gameserver/.venv/lib/python3.11/site-packages/django/test/testcases.py", line 284, in _setup_and_call
        self._post_teardown()
      File "/home/test/ctf-gameserver/.venv/lib/python3.11/site-packages/django/test/testcases.py", line 1006, in _post_teardown
        self._fixture_teardown()
      File "/home/test/ctf-gameserver/.venv/lib/python3.11/site-packages/django/test/testcases.py", line 1038, in _fixture_teardown
        call_command('flush', verbosity=0, interactive=False,
      File "/home/test/ctf-gameserver/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 181, in call_command
        return command.execute(*args, **defaults)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/test/ctf-gameserver/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 398, in execute
        output = self.handle(*args, **options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/test/ctf-gameserver/.venv/lib/python3.11/site-packages/django/core/management/commands/flush.py", line 65, in handle
        raise CommandError(
    django.core.management.base.CommandError: Database file:memorydb_default?mode=memory&cache=shared couldn't be flushed. Possible reasons:
      * The database isn't running or isn't configured correctly.
      * At least one of the expected database tables doesn't exist.
      * The SQL was invalid.
    Hint: Look at the output of 'django-admin sqlflush'. That's the SQL this command wasn't able to run.

One possible reason for the "database table is locked" error is
mentioned in https://code.djangoproject.com/ticket/29280: It can occur
when multiple threads access a database simultaneously and one thread
already has a read lock and tries to upgrade it to a write lock. If that
fails because the write lock is already taken then this exception is
thrown (to prevent deadlocking the database). However, the suggested fix
(replacing "BEGIN" with "BEGIN IMMEDIATE" to take the write lock
immediately) did not change the result in our case.

There must be some other race condition which is only triggered now,
most likely in some updated dependency.

But the actual solution is simple: Wait until the scoreboard thread has
finished. It was always buggy to keep it running while Django attempts
to cleanup the database concurrently.